services:
  - type: web
    name: polyclique-api
    env: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false # Tu devras saisir la valeur d'Aiven dans le dashboard Render
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

